baseurl = "https://thelifekiss.com/"
languageCode = "en-us"
title = "Knowledge is power"
# Define how many pages appear per site
paginate = 8
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "thelifekiss-com"
# Enable google analytics by entering your tracking code
googleAnalytics = "UA-72465781-2"
theme = "hugo-minimalist-theme"

[params]
    site_author = "Vũ Kim Thành"
    site_description = "Knowledge is power"
    site_image = ""
    location = "Hà Nội, Việt Nam"
    # Link custom assets relative to /static
    avatar = "img/profile-image.jpg"
    header_background = "img/header-bg-study-light.jpg"
    header_title = "Knowledge is power"
    header_quotations = "Hãy học khi người khác ngủ. Lao động khi người khác lười nhác. Chuẩn bị khi người khác chơi bời và có giấc mơ khi người khác chỉ ao ước."
    keywords = "Web, HTML, CSS, JavaScript, Front-end, Blockchain, Segwit"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable google analytics by entering your tracking code
    google_analytics = "UA-72465781-2"

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "thanh_sky"
    facebook  = "thanhvk31"
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = ""
    gplus     = ""
